# Generated by Django 3.2.8 on 2023-01-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='singer',
            field=models.CharField(default='歌手', max_length=200),
            preserve_default=False,
        ),
    ]
