# Generated by Django 4.1.5 on 2023-01-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='composition',
            field=models.CharField(default='--', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='singer',
            field=models.CharField(default='--', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(default='--'),
            preserve_default=False,
        ),
    ]
