# Generated by Django 3.2.8 on 2023-01-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_article_singer'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='composition',
            field=models.CharField(default='作曲', max_length=200),
            preserve_default=False,
        ),
    ]
